### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Kriikle** [Kriikle/PHP_studing#10]
- [ ] Добавить код стандарт фиксер ([php fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer))
- [ ] Развернуть в докере 
- [ ] Php unit test
- [ ] Очистить от комментариев и дампов 
- [ ] Namespace use почистить и типизация методов declare type strict types = 1
